import type { Metadata } from "next";
import "./globals.scss";
import Header from "./components/layout/Header";
import Main from "./components/layout/Main";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
      >
        <Header />
        <Main>
          {children}
        </Main>
      </body>
    </html>
  );
}
