import { Inter } from "next/font/google";
// import { Khula } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/Layout/NavBar/NavBar";
import SocialMedia from "@/Components/Global/SocialMedia/SocialMedia";
import Footer from "@/Components/Layout/Footer/Footer";
import Mouse from "@/Components/Layout/Mouse/Mouse";

// import Animation from "./Animation";

const inter = Inter({ subsets: ["latin"] });
// const khula = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "R_Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {/* <SocialMedia/> */}
        {children}
        {/* <Animation/> */}
        {/* <Mouse/> */}
        <Footer/>
      </body>
    </html>
  );
}
